const STORAGE_KEY = "mini-md-bot-client-v5";
const stickers = ["🔥", "✅", "🐛", "🚀", "💡", "🎯", "🤖", "🧩"];

const el = {
  saveApiBtn: document.getElementById("saveApiBtn"), downloadSessionBtn: document.getElementById("downloadSessionBtn"), saveStatus: document.getElementById("saveStatus"),
  sessionId: document.getElementById("sessionId"), deviceName: document.getElementById("deviceName"), phoneNumber: document.getElementById("phoneNumber"), pairCode: document.getElementById("pairCode"), generatePairBtn: document.getElementById("generatePairBtn"), codeInput: document.getElementById("codeInput"),
  groupId: document.getElementById("groupId"), groupName: document.getElementById("groupName"), groupJid: document.getElementById("groupJid"), memberInput: document.getElementById("memberInput"), addMemberBtn: document.getElementById("addMemberBtn"), adminInput: document.getElementById("adminInput"), addAdminBtn: document.getElementById("addAdminBtn"), memberList: document.getElementById("memberList"), adminList: document.getElementById("adminList"),
  welcomeToggle: document.getElementById("welcomeToggle"), antiLinkToggle: document.getElementById("antiLinkToggle"), muteToggle: document.getElementById("muteToggle"), protectSpamToggle: document.getElementById("protectSpamToggle"), protectToxicToggle: document.getElementById("protectToxicToggle"), protectLockToggle: document.getElementById("protectLockToggle"), protectAdminOnlyToggle: document.getElementById("protectAdminOnlyToggle"), protectApproveToggle: document.getElementById("protectApproveToggle"), saveGroupBtn: document.getElementById("saveGroupBtn"), saveProtectionBtn: document.getElementById("saveProtectionBtn"), adminActor: document.getElementById("adminActor"), adminTarget: document.getElementById("adminTarget"), adminActionType: document.getElementById("adminActionType"), runAdminActionBtn: document.getElementById("runAdminActionBtn"),
  stickerCaption: document.getElementById("stickerCaption"), stickerGrid: document.getElementById("stickerGrid"), selectedSticker: document.getElementById("selectedSticker"), generateStickerBtn: document.getElementById("generateStickerBtn"),
  imagePrompt: document.getElementById("imagePrompt"), generateImageBtn: document.getElementById("generateImageBtn"), generatedImageLink: document.getElementById("generatedImageLink"), toolsOutput: document.getElementById("toolsOutput"),
  socialPlatform: document.getElementById("socialPlatform"), socialUrl: document.getElementById("socialUrl"), downloadSocialBtn: document.getElementById("downloadSocialBtn"), songQuery: document.getElementById("songQuery"), songArtist: document.getElementById("songArtist"), downloadSongBtn: document.getElementById("downloadSongBtn"),
  igUrl: document.getElementById("igUrl"), ttUrl: document.getElementById("ttUrl"), fbUrl: document.getElementById("fbUrl"), downloadIgBtn: document.getElementById("downloadIgBtn"), downloadTtBtn: document.getElementById("downloadTtBtn"), downloadFbBtn: document.getElementById("downloadFbBtn"),
  stalkerActor: document.getElementById("stalkerActor"), stalkerAction: document.getElementById("stalkerAction"), stalkerTarget: document.getElementById("stalkerTarget"), trackStalkerBtn: document.getElementById("trackStalkerBtn"), refreshStalkerBtn: document.getElementById("refreshStalkerBtn"), stalkerList: document.getElementById("stalkerList"),
  socialStalkerPlatform: document.getElementById("socialStalkerPlatform"), socialStalkerUser: document.getElementById("socialStalkerUser"), socialStalkerType: document.getElementById("socialStalkerType"), socialStalkerNotes: document.getElementById("socialStalkerNotes"), trackSocialStalkerBtn: document.getElementById("trackSocialStalkerBtn"), refreshSocialStalkerBtn: document.getElementById("refreshSocialStalkerBtn"), socialStalkerList: document.getElementById("socialStalkerList"),
  mlUserId: document.getElementById("mlUserId"), mlServerId: document.getElementById("mlServerId"), mlRank: document.getElementById("mlRank"), mlHero: document.getElementById("mlHero"), stalkMlBtn: document.getElementById("stalkMlBtn"),
  npmPackage: document.getElementById("npmPackage"), npmVersion: document.getElementById("npmVersion"), stalkNpmBtn: document.getElementById("stalkNpmBtn"),
  githubUser: document.getElementById("githubUser"), stalkGithubBtn: document.getElementById("stalkGithubBtn"), refreshTechStalkBtn: document.getElementById("refreshTechStalkBtn"), techStalkOutput: document.getElementById("techStalkOutput"),
  funPrivateUser: document.getElementById("funPrivateUser"), funPrivateAction: document.getElementById("funPrivateAction"), runFunPrivateBtn: document.getElementById("runFunPrivateBtn"),
  funGroupId: document.getElementById("funGroupId"), funGroupAction: document.getElementById("funGroupAction"), runFunGroupBtn: document.getElementById("runFunGroupBtn"),
  gameType: document.getElementById("gameType"), gamePlayer: document.getElementById("gamePlayer"), playGameBtn: document.getElementById("playGameBtn"), refreshScoresBtn: document.getElementById("refreshScoresBtn"), gameScoresList: document.getElementById("gameScoresList"),
  aiPrompt: document.getElementById("aiPrompt"), askAiBtn: document.getElementById("askAiBtn"), aiReply: document.getElementById("aiReply"),
  ownerName: document.getElementById("ownerName"), ownerNumber: document.getElementById("ownerNumber"), ownerMode: document.getElementById("ownerMode"), ownerEval: document.getElementById("ownerEval"), loadOwnerBtn: document.getElementById("loadOwnerBtn"), saveOwnerBtn: document.getElementById("saveOwnerBtn"),
  menuName: document.getElementById("menuName"), getMenuBtn: document.getElementById("getMenuBtn"), getAllmenuBtn: document.getElementById("getAllmenuBtn"), menuOutput: document.getElementById("menuOutput"),
  downloadCodeBtn: document.getElementById("downloadCodeBtn"), downloadGroupBtn: document.getElementById("downloadGroupBtn"), downloadStalkerBtn: document.getElementById("downloadStalkerBtn"), downloadApiSessionBtn: document.getElementById("downloadApiSessionBtn"),
};

let state = { selectedSticker: "", members: [], admins: [], stalkerEvents: [], socialStalkerEvents: [], gameScores: [] };

const groupPayload = () => ({ id: el.groupId.value.trim() || "main-group", name: el.groupName.value.trim(), jid: el.groupJid.value.trim(), members: state.members, admins: state.admins, features: { welcome: el.welcomeToggle.checked, antiLink: el.antiLinkToggle.checked, muteNight: el.muteToggle.checked }, protection: { antiLink: el.antiLinkToggle.checked, antiSpam: el.protectSpamToggle.checked, antiToxic: el.protectToxicToggle.checked, lockGroup: el.protectLockToggle.checked, adminOnly: el.protectAdminOnlyToggle.checked, approveMembers: el.protectApproveToggle.checked } });
const sessionPayload = () => ({ id: el.sessionId.value.trim() || "main-session", deviceName: el.deviceName.value.trim(), phoneNumber: el.phoneNumber.value.trim(), pairCode: el.pairCode.value, codeInput: el.codeInput.value, group: groupPayload(), sticker: { emoji: state.selectedSticker, caption: el.stickerCaption.value } });
const setStatus = (t) => { el.saveStatus.textContent = t; };

function saveLocal(){ localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...state, form: sessionPayload() })); setStatus(`Autosaved: ${new Date().toLocaleTimeString()}`); }
function loadLocal(){ const raw = localStorage.getItem(STORAGE_KEY); if(!raw) return; const c = JSON.parse(raw); state = { ...state, ...c }; const f = c.form || {}; el.sessionId.value=f.id||""; el.deviceName.value=f.deviceName||""; el.phoneNumber.value=f.phoneNumber||""; el.pairCode.value=f.pairCode||""; el.codeInput.value=f.codeInput||""; el.groupId.value=f.group?.id||""; el.groupName.value=f.group?.name||""; el.groupJid.value=f.group?.jid||""; el.welcomeToggle.checked=!!f.group?.features?.welcome; el.antiLinkToggle.checked=!!f.group?.features?.antiLink; el.muteToggle.checked=!!f.group?.features?.muteNight; el.protectSpamToggle.checked=!!f.group?.protection?.antiSpam; el.protectToxicToggle.checked=!!f.group?.protection?.antiToxic; el.protectLockToggle.checked=!!f.group?.protection?.lockGroup; el.protectAdminOnlyToggle.checked=!!f.group?.protection?.adminOnly; el.protectApproveToggle.checked=!!f.group?.protection?.approveMembers; el.stickerCaption.value=f.sticker?.caption||""; }
function download(name, content, type="text/plain"){ const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); }
async function api(path, method="GET", body){ const res=await fetch(path,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined}); if(!res.ok) throw new Error(`API ${path} failed`); return res.json(); }

function renderMembers(){ el.memberList.innerHTML=""; state.members.forEach((m,i)=>{ const li=document.createElement("li"); li.textContent=`${m} (remove)`; li.onclick=()=>{state.members.splice(i,1); renderMembers(); saveLocal();}; el.memberList.appendChild(li);}); if(!state.members.length) el.memberList.innerHTML="<li>No members</li>"; }
function renderAdmins(){ el.adminList.innerHTML=""; state.admins.forEach((m,i)=>{ const li=document.createElement("li"); li.textContent=`${m} (remove admin)`; li.onclick=()=>{state.admins.splice(i,1); renderAdmins(); saveLocal();}; el.adminList.appendChild(li);}); if(!state.admins.length) el.adminList.innerHTML="<li>No admins</li>"; }
function renderStickers(){ el.stickerGrid.innerHTML=""; stickers.forEach((s)=>{ const b=document.createElement("button"); b.className=`sticker ${state.selectedSticker===s?"active":""}`; b.textContent=s; b.onclick=()=>{state.selectedSticker=s; renderStickers(); saveLocal();}; el.stickerGrid.appendChild(b);}); el.selectedSticker.textContent=state.selectedSticker||"None"; }
function renderStalker(){ el.stalkerList.innerHTML=""; state.stalkerEvents.forEach((e)=>{ const li=document.createElement("li"); li.textContent=`${e.at} | ${e.actor} ${e.action} ${e.target}`; el.stalkerList.appendChild(li);}); if(!state.stalkerEvents.length) el.stalkerList.innerHTML="<li>No events</li>"; }
function renderSocialStalker(){ el.socialStalkerList.innerHTML=""; state.socialStalkerEvents.forEach((e)=>{ const li=document.createElement("li"); li.textContent=`${e.at} | ${e.platform} @${e.username} | ${e.eventType}`; el.socialStalkerList.appendChild(li);}); if(!state.socialStalkerEvents.length) el.socialStalkerList.innerHTML="<li>No social stalker events</li>"; }
function renderScores(){ el.gameScoresList.innerHTML=""; state.gameScores.forEach((g)=>{ const li=document.createElement("li"); li.textContent=`${g.at} | ${g.player} - ${g.game}: ${g.score} (${g.result})`; el.gameScoresList.appendChild(li);}); if(!state.gameScores.length) el.gameScoresList.innerHTML="<li>No scores yet</li>"; }

function bind(){
  [el.sessionId,el.deviceName,el.phoneNumber,el.codeInput,el.groupId,el.groupName,el.groupJid,el.welcomeToggle,el.antiLinkToggle,el.muteToggle,el.protectSpamToggle,el.protectToxicToggle,el.protectLockToggle,el.protectAdminOnlyToggle,el.protectApproveToggle,el.stickerCaption,el.imagePrompt,el.aiPrompt,el.ownerName,el.ownerNumber,el.ownerMode,el.menuName,el.socialPlatform,el.socialUrl,el.songQuery,el.songArtist,el.igUrl,el.ttUrl,el.fbUrl,el.mlUserId,el.mlServerId,el.mlRank,el.mlHero,el.npmPackage,el.npmVersion,el.githubUser,el.funPrivateUser,el.funPrivateAction,el.funGroupId,el.funGroupAction,el.gameType,el.gamePlayer].forEach((n)=> n?.addEventListener("input",saveLocal));

  el.generatePairBtn.onclick=()=>{ el.pairCode.value=`${Math.random().toString(36).slice(2,8).toUpperCase()}-${Date.now().toString().slice(-4)}`; saveLocal(); };
  el.addMemberBtn.onclick=()=>{ const v=el.memberInput.value.trim(); if(!v) return; state.members.push(v); el.memberInput.value=""; renderMembers(); saveLocal(); };
  el.addAdminBtn.onclick=()=>{ const v=el.adminInput.value.trim(); if(!v) return; if(!state.admins.includes(v)) state.admins.push(v); el.adminInput.value=""; renderAdmins(); saveLocal(); };

  el.saveApiBtn.onclick=async()=>{ const d=await api('/api/session','POST',sessionPayload()); setStatus(`Saved API session: ${d.session.id}`); };
  el.downloadSessionBtn.onclick=()=>download('session.json',JSON.stringify(sessionPayload(),null,2),'application/json');
  el.saveGroupBtn.onclick=async()=>{ await api('/api/groups','POST',groupPayload()); setStatus('Group saved to API'); };
  el.saveProtectionBtn.onclick=async()=>{ const p=groupPayload(); const d=await api('/api/groups/protection','POST',{id:p.id,...p.protection}); el.toolsOutput.value=JSON.stringify(d,null,2); setStatus('Group protection saved'); };
  el.runAdminActionBtn.onclick=async()=>{ const d=await api('/api/groups/admin-action','POST',{id:el.groupId.value.trim()||'main-group',actor:el.adminActor.value.trim(),target:el.adminTarget.value.trim(),action:el.adminActionType.value}); state.admins=d.group.admins||state.admins; state.members=d.group.members||state.members; renderAdmins(); renderMembers(); el.toolsOutput.value=JSON.stringify(d.result,null,2); setStatus('Admin action executed'); };

  el.generateStickerBtn.onclick=async()=>{ const d=await api('/api/sticker/generate','POST',{sticker:state.selectedSticker,caption:el.stickerCaption.value}); el.toolsOutput.value=JSON.stringify(d.stickerPack,null,2); setStatus('Sticker API generated'); };
  el.generateImageBtn.onclick=async()=>{ const d=await api('/api/tools/image-generate','POST',{prompt:el.imagePrompt.value}); el.generatedImageLink.href=d.image.url; el.generatedImageLink.textContent=d.image.url; el.toolsOutput.value=JSON.stringify(d.image,null,2); setStatus('Image generated API'); };

  el.downloadSocialBtn.onclick=async()=>{ const d=await api('/api/download/social-media','POST',{platform:el.socialPlatform.value,url:el.socialUrl.value,quality:'hd'}); el.toolsOutput.value=JSON.stringify(d.item,null,2); setStatus(`Social media download ready: ${d.item.platform}`); };
  el.downloadSongBtn.onclick=async()=>{ const d=await api('/api/download/song','POST',{query:el.songQuery.value,artist:el.songArtist.value,format:'mp3'}); el.toolsOutput.value=JSON.stringify(d.item,null,2); setStatus(`Song download ready: ${d.item.query}`); };
  el.downloadIgBtn.onclick=async()=>{ const d=await api('/api/download/instagram','POST',{url:el.igUrl.value,quality:'hd'}); el.toolsOutput.value=JSON.stringify(d.item,null,2); setStatus('Instagram download ready'); };
  el.downloadTtBtn.onclick=async()=>{ const d=await api('/api/download/tiktok','POST',{url:el.ttUrl.value,quality:'hd'}); el.toolsOutput.value=JSON.stringify(d.item,null,2); setStatus('TikTok download ready'); };
  el.downloadFbBtn.onclick=async()=>{ const d=await api('/api/download/facebook','POST',{url:el.fbUrl.value,quality:'hd'}); el.toolsOutput.value=JSON.stringify(d.item,null,2); setStatus('Facebook download ready'); };

  el.trackStalkerBtn.onclick=async()=>{ const d=await api('/api/stalker','POST',{actor:el.stalkerActor.value,action:el.stalkerAction.value,target:el.stalkerTarget.value}); state.stalkerEvents.unshift(d.event); state.stalkerEvents=state.stalkerEvents.slice(0,100); renderStalker(); saveLocal(); };
  el.refreshStalkerBtn.onclick=async()=>{ const d=await api('/api/stalker'); state.stalkerEvents=d.events||[]; renderStalker(); saveLocal(); };
  el.trackSocialStalkerBtn.onclick=async()=>{ const d=await api('/api/stalker/social-media','POST',{platform:el.socialStalkerPlatform.value,username:el.socialStalkerUser.value,eventType:el.socialStalkerType.value,notes:el.socialStalkerNotes.value}); state.socialStalkerEvents.unshift(d.event); state.socialStalkerEvents=state.socialStalkerEvents.slice(0,100); renderSocialStalker(); saveLocal(); };
  el.refreshSocialStalkerBtn.onclick=async()=>{ const d=await api('/api/stalker/social-media'); state.socialStalkerEvents=d.events||[]; renderSocialStalker(); saveLocal(); };

  el.stalkMlBtn.onclick=async()=>{ const d=await api('/api/stalk/ml','POST',{userId:el.mlUserId.value,serverId:el.mlServerId.value,rank:el.mlRank.value,hero:el.mlHero.value}); el.techStalkOutput.value=JSON.stringify(d.row,null,2); setStatus('ML stalk tracked'); };
  el.stalkNpmBtn.onclick=async()=>{ const d=await api('/api/stalk/npm','POST',{packageName:el.npmPackage.value,version:el.npmVersion.value}); el.techStalkOutput.value=JSON.stringify(d.row,null,2); setStatus('NPM stalk tracked'); };
  el.stalkGithubBtn.onclick=async()=>{ const d=await api('/api/stalk/github','POST',{username:el.githubUser.value}); el.techStalkOutput.value=JSON.stringify(d.row,null,2); setStatus('GitHub stalk tracked'); };
  el.refreshTechStalkBtn.onclick=async()=>{ const d=await api('/api/stalk/all'); el.techStalkOutput.value=JSON.stringify(d.data,null,2); setStatus('Tech stalk data refreshed'); };

  el.runFunPrivateBtn.onclick=async()=>{ const d=await api('/api/fun/private','POST',{user:el.funPrivateUser.value,action:el.funPrivateAction.value}); el.toolsOutput.value=JSON.stringify(d.row,null,2); setStatus('Private fun executed'); };
  el.runFunGroupBtn.onclick=async()=>{ const d=await api('/api/fun/group','POST',{groupId:el.funGroupId.value,action:el.funGroupAction.value}); el.toolsOutput.value=JSON.stringify(d.row,null,2); setStatus('Group fun executed'); };

  el.playGameBtn.onclick=async()=>{ const d=await api('/api/games/play','POST',{game:el.gameType.value,player:el.gamePlayer.value}); state.gameScores.unshift(d.row); state.gameScores=state.gameScores.slice(0,100); renderScores(); saveLocal(); };
  el.refreshScoresBtn.onclick=async()=>{ const d=await api('/api/games/scores'); state.gameScores=d.scores||[]; renderScores(); saveLocal(); };

  el.askAiBtn.onclick=async()=>{ const d=await api('/api/ai/chat','POST',{prompt:el.aiPrompt.value}); el.aiReply.value=d.reply; setStatus(`AI replied using ${d.model}`); };
  el.loadOwnerBtn.onclick=async()=>{ const d=await api('/api/owner'); el.ownerName.value=d.owner.ownerName; el.ownerNumber.value=d.owner.ownerNumber; el.ownerMode.value=d.owner.mode; el.ownerEval.checked=!!d.owner.allowEval; saveLocal(); };
  el.saveOwnerBtn.onclick=async()=>{ await api('/api/owner','POST',{ownerName:el.ownerName.value,ownerNumber:el.ownerNumber.value,mode:el.ownerMode.value,allowEval:el.ownerEval.checked}); setStatus('Owner saved'); };

  el.getMenuBtn.onclick=async()=>{ const name=(el.menuName.value||'main').trim(); const d=await api(`/api/menu?name=${encodeURIComponent(name)}`); el.menuOutput.value=JSON.stringify(d,null,2); setStatus(`Loaded menu: ${name||'main'}`); };
  el.getAllmenuBtn.onclick=async()=>{ const d=await api('/api/allmenu'); el.menuOutput.value=JSON.stringify(d,null,2); setStatus('Loaded allmenu'); };

  el.downloadCodeBtn.onclick=()=>download('bot-code.txt',el.codeInput.value||'');
  el.downloadGroupBtn.onclick=()=>download('group.json',JSON.stringify(groupPayload(),null,2),'application/json');
  el.downloadStalkerBtn.onclick=()=>download('stalker.json',JSON.stringify({general:state.stalkerEvents,social:state.socialStalkerEvents},null,2),'application/json');
  el.downloadApiSessionBtn.onclick=()=>{ const id=el.sessionId.value.trim()||'main-session'; window.open(`/api/download/session/${encodeURIComponent(id)}`,'_blank'); };
}

bind(); loadLocal(); renderMembers(); renderAdmins(); renderStickers(); renderStalker(); renderSocialStalker(); renderScores(); setInterval(saveLocal, 1500);
